version: '3.7'

services:

  frontend:
    container_name: frontend
    build: .
    volumes:
      - .:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    hostname: frontend
    restart: unless-stopped
    env_file: .env
